### ISSUE TITLE
No working

### ISSUE THREAD

**Issue by smleca** [carlos1172/ProgressBarTimeLeft#10]
![image](https://user-images.githubusercontent.com/45450249/178522716-a5e62212-01c9-4637-a3a9-1baa44ead923.png)

**Comment by carlos1172** [comment]
Reinstall the addon

**Comment by sandroboris** [comment]
Hello. I tried to reinstall. But, the error is still there
![Capture d’écran 2022-07-13 022314](https://user-images.githubusercontent.com/109185831/178615250-686fbeca-13bc-4e1a-9601-284daba71d60.png)
.

**Comment by sandroboris** [comment]
It worked. I reinstalled it from the zip file. No more error. My english is very bad. Sorry.

**Comment by 425833137** [comment]
after I update anki to 2.1.54（qt6），this addons does not work. plz fix this bug, I really love this addons❤

Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Windows 10
Flags: frz=True ao=True sv=?
Add-ons, last update check: 2022-07-19 16:36:37

Caught exception:
Traceback (most recent call last):
  File "aqt.progress", line 118, in handler
  File "aqt.main", line 197, in on_window_init
  File "aqt.main", line 243, in setupProfileAfterWebviewsLoaded
  File "aqt.main", line 288, in setupProfile
  File "aqt.main", line 294, in showProfileManager
  File "aqt.main", line 676, in moveToState
  File "aqt.hooks_gen", line 3797, in __call__
  File "anki.hooks", line 34, in runHook
  File "C:\Users\42583\AppData\Roaming\Anki2\addons21\1097423555\reviewer_progress_bar.py", line 849, in afterStateChangeCallBack
    currDID = mw.col.decks.current()['id']
AttributeError: 'NoneType' object has no attribute 'decks'

**Comment by carlos1172** [comment]
The addon currently doesn't work with multiple Anki profiles. Hold shift when turning on Anki, delete all other profiles aside from your main profile, and it should work.

**Comment by 425833137** [comment]
> The addon currently doesn't work with multiple Anki profiles. Hold shift when turning on Anki, delete all other profiles aside from your main profile, and it should work.
> […](#)
> On Jul 19, 2022, 5:04 PM +0800, 425833137 ***@***.***>, wrote: after I update anki to 2.1.54（qt6），this addons does not work. plz fix this bug, I really love this addons❤ Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1 Platform: Windows 10 Flags: frz=True ao=True sv=? Add-ons, last update check: 2022-07-19 16:36:37 Caught exception: Traceback (most recent call last): File "aqt.progress", line 118, in handler File "aqt.main", line 197, in on_window_init File "aqt.main", line 243, in setupProfileAfterWebviewsLoaded File "aqt.main", line 288, in setupProfile File "aqt.main", line 294, in showProfileManager File "aqt.main", line 676, in moveToState File "aqt.hooks_gen", line 3797, in call File "anki.hooks", line 34, in runHook File "C:\Users\42583\AppData\Roaming\Anki2\addons21\1097423555\reviewer_progress_bar.py", line 849, in afterStateChangeCallBack currDID = mw.col.decks.current()['id'] AttributeError: 'NoneType' object has no attribute 'decks' — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

I can use this addons in anki 2.1.49 with multiple Anki profiles, but in 2.1.54 it has this bug

**Comment by carlos1172** [comment]
Yes I'm aware, but that's the only fix at the moment

**Comment by carlos1172** [comment]
Same as issue #6
